server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/auth_db
    username: root
    password: Francesco90
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: auth-service

  profiles:
    active: dev

jwt:
  # chiave usata per firmare i token; deve coincidere con quella del Gateway
  secret: ${JWT_SECRET:myTopSecretKey}

admin:
  email: f.chifari22@gmail.com
  password: NewPass123@

---
spring:
  config:
    activate:
      on-profile: dev

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha